name: Generate Profile Image

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  
jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Execute HTTP Request
        uses: actions/checkout@v2

      - name: Generate Image
        run: curl -o profile-image.png "https://github-readme-stats-nekzus.vercel.app/api/top-langs/?username=Nekzus&cache_seconds=86400&hide=css%2Chtml%2Cless&layout=compact&langs_count=10&hide_border=false&role=owner-collaborator&theme=dark&bg_color=000000"

      - name: Upload Image
        uses: actions/upload-artifact@v2
        with:
          name: profile-image
          path: profile-image.png
