name: Generar im치genes de perfil

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar solicitud HTTP
        uses: actions/checkout@v3

      - name: Generar im치genes en modo oscuro
        run: |
          curl -o assets/top-langs-dark.svg "https://github-readme-stats-nekzus.vercel.app/api/top-langs/?username=Nekzus&hide=css%2Chtml%2Cless&layout=compact&langs_count=10&hide_border=false&role=owner-collaborator&theme=dark&bg_color=000000"
          curl -o assets/gh-stats-dark.svg "https://github-readme-stats-nekzus.vercel.app/api?username=Nekzus&show_icons=true&count_private=true&line_height=28&hide_border=false&card_width=450&include_all_commits=true&role=owner-collaborator&exclude_repo=github-readme-stats&theme=dark&bg_color=000000&rank_icon=default"

      - name: Generar im치genes en modo claro
        run: |
          curl -o assets/top-langs-light.svg "https://github-readme-stats-nekzus.vercel.app/api/top-langs/?username=Nekzus&hide=css%2Chtml%2Cless&layout=compact&langs_count=10&hide_border=false&border_color=000000&role=owner-collaborator&theme=default"
          curl -o assets/gh-stats-light.svg "https://github-readme-stats-nekzus.vercel.app/api?username=Nekzus&show_icons=true&count_private=true&line_height=28&hide_border=false&border_color=000000&card_width=450&include_all_commits=true&role=owner-collaborator&exclude_repo=github-readme-stats&theme=default&rank_icon=default"

      - name: Verificar archivos generados
        run: ls assets

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Agregar y confirmar cambios
        run: |
          git add assets/top-langs-dark.svg assets/gh-stats-dark.svg assets/top-langs-light.svg assets/gh-stats-light.svg
          git commit -m "Actualizar im치genes de perfil"

      - name: Commit y push al repositorio
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}
