name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"

